services:
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:latest
    container_name: komodo-periphery
    labels:
      komodo.skip:
    restart: unless-stopped
    environment:
      PERIPHERY_ROOT_DIRECTORY: /etc/komodo
      PERIPHERY_PASSKEYS: ${PERIPHERY_PASSKEYS}
      PERIPHERY_SSL_ENABLED: false
      PERIPHERY_DISABLE_TERMINALS: false
      PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/proc
      - /etc/komodo:/etc/komodo
    ports:
      - ${TS_IP}:8121:8120
