services:
  mongo:
    image: mongo
    container_name: komodo-mongo
    labels:
      komodo.skip:
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    volumes:
      - ./data/db/mongo-data:/data/db
      - ./data/db/mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"

  core:
    image: ghcr.io/moghtech/komodo-core:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: komodo-core
    labels:
      komodo.skip:
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 127.0.0.1:9122:9120
      - ${TS_IP}:9122:9120
    env_file: ./.env
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
    volumes:
      - ./data/core/repo-cache:/repo-cache
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"

  periphery:
    image: ghcr.io/moghtech/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: komodo-periphery
    labels:
      komodo.skip:
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/proc
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"
