services:
  tianji:
    image: moonrailgun/tianji
    ports:
      - "127.0.0.1:12345:12345"
      - "192.168.10.20:12345:12345" #replace ip with tailscale or local
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      ALLOW_REGISTER: "true"
      ALLOW_OPENAPI: "false"
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./tianji_db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
