services:
  server-bot:
    container_name: pangolin-discord-bot
    image: hhftechnology/pangolin-discord-bot:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backups:/app/backups
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /root:/root:ro
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - BACKUP_DIR=/app/backups
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
    restart: unless-stopped
