name: wg-easy
services:
    wg-easy:
        container_name: wg-easy
        environment:
            - LANG=en
            - WG_HOST=<host_server_ip_address> #ip address or myserver.domain.com
            - PASSWORD_HASH=$$2a$$16$$y20H7D7mPmL.bxxxxxxxxxxxxxxxxxxxxx #bcrypt hash - replace single $ with double $$
            - PORT=51821
            - WG_PORT=51820
            - WG_DEFAULT_DNS=1.1.1.1, 8.8.8.8 #replace if you want with NextDNS
            - UI_TRAFFIC_STATS=true
        volumes:
            - ~/.wg-easy:/etc/wireguard
        ports:
            - 51820:51820/udp
            - 51821:51821/tcp
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
            - net.ipv4.ip_forward=1
        restart: unless-stopped
        image: ghcr.io/wg-easy/wg-easy
