version: 0.1
log:
  level: info
  formatter: text
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :5000
  secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # some log string

notifications:
  endpoints:
    - name: "mycustomntfyreceiver"
      url: "http://registry-webhook-receiver:5001/notify"
      timeout: 5s
      threshold: 3
      backoff: 10s
