networks:
  registry-net:
    driver: bridge

services:
  # --- registry ---
  registry:
    image: registry:3.0.0
    container_name: registry_service
    volumes:
      - ./docker-registry/data:/var/lib/registry
    networks:
      - registry-net
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      OTEL_TRACES_EXPORTER: "none"
      REGISTRY_LOG_LEVEL: "info"
      REGISTRY_HTTP_SECRET: ${REGISTRY_HTTP_SECRET}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  # --- proxy ---
  caddy:
    image: caddy:2.10.0
    container_name: caddy_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      - registry-net
    restart: unless-stopped
    depends_on:
      - registry
      - registry-ui
      - portainer
      - prometheus
      - grafana
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

  # --- ui ---
  registry-ui:
    image: joxit/docker-registry-ui:2.5.7
    container_name: registry_ui
    networks:
      - registry-net
    depends_on:
      - registry
    environment:
      NGINX_PROXY_PASS_URL: "http://registry:5000"
      DELETE_IMAGES: "true"
      SINGLE_REGISTRY: "true"
      REGISTRY_TITLE: ${REGISTRY_TITLE}
      PULL_URL: ${PULL_URL}
      THEME: "dark"
      THEME_PRIMARY_TEXT: "#e5e7eb"
      THEME_NEUTRAL_TEXT: "#6b7280"
      THEME_BACKGROUND: "#111827"
      THEME_HOVER_BACKGROUND: "#1f2937"
      THEME_ACCENT_TEXT: "#14b8a6"
      THEME_HEADER_TEXT: "#e5e7eb"
      THEME_HEADER_ACCENT_TEXT: "#5eead4"
      THEME_HEADER_BACKGROUND: "#1f2937"
      THEME_FOOTER_TEXT: "#e5e7eb"
      THEME_FOOTER_NEUTRAL_TEXT: "#9ca3af"
      THEME_FOOTER_BACKGROUND: "#1f2937"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M


  # --- REGSYNC SERVICE ---
  regsync:
    image: ghcr.io/regclient/regsync:v0.8.3
    container_name: regsync_service
    command: ["-c", "/config/regsync.yml", "server"]
    volumes:
      - ./regsync.yml:/config/regsync.yml:ro
      - ./secrets:/secrets:ro
    networks:
      - registry-net
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  # --- REGBOT SERVICE ---
  regbot:
    image: ghcr.io/regclient/regbot:v0.8.3
    container_name: regbot_service
    command: ["-c", "/config/regbot.yml", "server"]
    volumes:
      - ./regbot.yml:/config/regbot.yml:ro
      - ./secrets:/secrets:ro
    networks:
      - registry-net
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  # --- Portainer Service ---
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    networks:
      - registry-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  # --- Prometheus Service ---
  prometheus:
    image: prom/prometheus:v3.3.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.listen-address=:9090'
    # ports:
      # - "9090:9090"
    networks:
      - registry-net
    logging:
      driver: "json-file"
      options: { max-size: "10m", max-file: "3" }
    deploy:
      resources:
        limits: { cpus: '0.50', memory: 512M }

  # --- Grafana Service ---
  grafana:
    image: grafana/grafana:12.0.0
    container_name: grafana
    restart: unless-stopped
    # ports:
      # - "3000:3000"
    volumes:
      - ./grafana/grafana-data:/var/lib/grafana
      - ./grafana/grafana-config:/etc/grafana
      - ./grafana/grafana-logs:/var/log/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
    networks:
      - registry-net
    logging:
      driver: "json-file"
      options: { max-size: "10m", max-file: "3" }
    deploy:
      resources:
        limits: { cpus: '0.50', memory: 512M }
