services:

  # --- registry ---
  registry:
    image: registry:3.0.0
    container_name: private_registry_service
    networks:
      - registry-net
    volumes:
      - ./docker-registry/data:/var/lib/registry
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      OTEL_TRACES_EXPORTER: "none"
      REGISTRY_LOG_LEVEL: "info"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  # --- proxy ---
  caddy:
    image: caddy:2.10.0
    container_name: caddy_proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - registry-net
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    restart: unless-stopped
    depends_on:
      - registry
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  # --- ui ---
  registry-ui:
    image: joxit/docker-registry-ui:2.5.7
    container_name: registry_ui
    networks:
      - registry-net
    environment:
      NGINX_PROXY_PASS_URL: "http://registry:5000"
      DELETE_IMAGES: "true"
      SINGLE_REGISTRY: "true"
      REGISTRY_TITLE: "Private Docker Registry"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

networks:
  registry-net:
    driver: bridge
