services:

  headscale:
    image: headscale/headscale:0.25.1
    pull_policy: always
    container_name: headscale
    restart: unless-stopped
    command: serve
    volumes:
      - ./headscale/config:/etc/headscale
      - ./headscale/data:/var/lib/headscale
    labels:
      - traefik.enable=true
      - traefik.http.routers.headscale-rtr.rule=Host(`${HS_URL}`) # add in .env
      - traefik.http.routers.headscale-rtr.priority=90
      - traefik.http.routers.headscale-rtr.entrypoints=websecure
      - traefik.http.routers.headscale-rtr.tls.certresolver=myresolver
      - traefik.http.services.headscale-svc.loadbalancer.server.port=8080
      - traefik.http.routers.headscale-rtr.middlewares=corsHeader@docker

  headscale-admin:
    image: goodieshq/headscale-admin:0.25.5
    pull_policy: always
    container_name: headscale-admin
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.headscale-admin-rtr.rule=Host(`${HUI_URL}`) && PathPrefix(`/admin`) # add in .env
      - traefik.http.routers.headscale-admin-rtr.entrypoints=websecure
      - traefik.http.routers.headscale-admin-rtr.tls.certresolver=myresolver
      - traefik.http.services.headscale-admin-svc.loadbalancer.server.port=80
      - traefik.http.routers.headscale-admin-rtr.middlewares=corsHeader@docker

  headplane:
    image: ghcr.io/tale/headplane:0.5.5
    pull_policy: always
    container_name: headplane
    restart: unless-stopped
    volumes:
      - ./headplane/config.yaml:/etc/headplane/config.yaml
      - ./headscale/config:/etc/headscale
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - headscale
    labels:
      - traefik.enable=true
      # Rule to match /admin path on the headscale host
      - traefik.http.routers.headplane-rtr.rule=Host(`${HS_URL}`) && PathPrefix(`/admin`) # add in .env
      # ADDED: Set priority HIGHER than headscale's router for the same host
      - traefik.http.routers.headplane-rtr.priority=100
      - traefik.http.routers.headplane-rtr.entrypoints=websecure
      - traefik.http.routers.headplane-rtr.tls.certresolver=myresolver
      - traefik.http.services.headplane-svc.loadbalancer.server.port=3000 # Headplane's internal port
      # Apply the modified CORS middleware
      - traefik.http.routers.headplane-rtr.middlewares=corsHeader@docker

  traefik:
    image: traefik:v3.3.4
    pull_policy: always
    restart: unless-stopped
    container_name: traefik
    command:
      - --log.filePath=/var/log/traefik.log
      - --accesslog=true
      - --log.level=INFO
      - --ping=true #testing health
      - --api=true
      - --api.dashboard=false
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=${LE_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/certificates/acme.json
      - --global.sendAnonymousUsage=false
      - --entrypoints.websecure.http.tls.options=securetls@file  # TLS configuration
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/certificates:/certificates
      - ./traefik/logs/traefik.log:/var/log/traefik.log
      - ./traefik/tls.yml:/tls.yml  # Custom TLS
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--output-document=/dev/null", "http://127.0.0.1:8080/ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 20s

    labels:
      # CORS middleware for API calls ---
      - traefik.http.middlewares.corsHeader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT
      - traefik.http.middlewares.corsHeader.headers.accesscontrolallowheaders=Authorization,*
      - traefik.http.middlewares.corsHeader.headers.accesscontrolalloworiginlist=https://${HUI_URL},https://${HS_URL} # add in .env
      - traefik.http.middlewares.corsHeader.headers.accesscontrolmaxage=100
      - traefik.http.middlewares.corsHeader.headers.addvaryheader=true
      
      # --- Redirect ${HUI_URL} root path (/) to /admin ---
      - traefik.http.middlewares.redirect-hui-root-to-admin.redirectregex.regex=^https?://([^/]+)/?$$
      - traefik.http.middlewares.redirect-hui-root-to-admin.redirectregex.replacement=https://$${1}/admin
      - traefik.http.middlewares.redirect-hui-root-to-admin.redirectregex.permanent=true
      - traefik.http.routers.hui-root-redirect.rule=Host(`${HUI_URL}`) && Path(`/`) # add in .env
      - traefik.http.routers.hui-root-redirect.entrypoints=websecure
      - traefik.http.routers.hui-root-redirect.tls.certresolver=myresolver
      - traefik.http.routers.hui-root-redirect.middlewares=redirect-hui-root-to-admin@docker

      # --- Redirect heads.${HS_URL} root path (/) to /admin ---
      - traefik.http.middlewares.redirect-hs-root-to-admin.redirectregex.regex=^https?://([^/]+)/?$$
      - traefik.http.middlewares.redirect-hs-root-to-admin.redirectregex.replacement=https://$${1}/admin
      - traefik.http.middlewares.redirect-hs-root-to-admin.redirectregex.permanent=true
      # Router for the root path of HS_URL
      - traefik.http.routers.hs-root-redirect.rule=Host(`${HS_URL}`) && Path(`/`) # add in .env
      - traefik.http.routers.hs-root-redirect.priority=95 # Higher than headscale (90), lower than headplane (100)
      - traefik.http.routers.hs-root-redirect.entrypoints=websecure
      - traefik.http.routers.hs-root-redirect.tls.certresolver=myresolver
      - traefik.http.routers.hs-root-redirect.middlewares=redirect-hs-root-to-admin@docker
      - traefik.http.routers.hs-root-redirect.service=noop@internal

      # --- Global Redirect HTTP to HTTPS ---
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
