# Goes in headplane dir. 
# headscale-deploy/
# ├── docker-compose.yaml
# ├── headplane/
# │   └── config.yaml


server:
  host: "0.0.0.0"
  port: 3000
  cookie_secret: "16151413121110090807060504030201" # Change this with exacly 32 cr
  cookie_secure: true

headscale:
  url: "http://headscale:8080"
  config_path: "/etc/headscale/config.yaml"
  config_strict: true

# Integration configurations
integration:
  docker:
    enabled: true
    container_name: "headscale"
    socket: "unix:///var/run/docker.sock"
  kubernetes:
    enabled: false
    validate_manifest: true
    pod_name: "headscale"
  proc:
    enabled: false
