server:
  host: "0.0.0.0"
  port: 3000
  cookie_secret: "e919exxxxxxxxxxxxxxxxxxxxx" # Change this!
  cookie_secure: true

headscale:
  url: "https://heads.example.com"  # change this
  config_path: "/etc/headscale/config.yaml"
  config_strict: true

# Integration configurations
integration:
  docker:
    enabled: true
    container_name: "headscale"
    socket: "unix:///var/run/docker.sock"
  kubernetes:
    enabled: false
    validate_manifest: true
    pod_name: "headscale"
  proc:
    enabled: false

# OIDC Configuration
oidc:
  issuer: "https://accounts.google.com"
  client_id: "147852369xxxxxxxxxxxxxxxxxxxxxxxxxxapps.googleusercontent.com" # change this
  client_secret_path: "/etc/headplane/secrets/oidc_client_secret" # container internal path mounted in docker-compose
  disable_api_key_login: false
  token_endpoint_auth_method: "client_secret_post"
  headscale_api_key: "O-0000000000000000000000000000" # change this
  redirect_uri: "https://heads.alisufyan.cloud/admin/oidc/callback"
  user_storage_file: "/var/lib/headplane/users.json"
