~/appdata/headscale-deploy/headplane$ cat config.yaml
server:
  host: "0.0.0.0"
  port: 3000
  cookie_secret: "xxxxxxxxxxxxxxxxxxxxxxx"
  cookie_secure: true

headscale:
  url: "https://hp.mydomain.tld"
  config_path: "/etc/headscale/config.yaml"
  config_strict: true

# Integration configurations
integration:
  agent:
    enabled: true
    pre_authkey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    host_name: "headplane-agent"
    cache_ttl: 60
    cache_path: "/var/lib/headplane/agent_cache.json"
    work_dir: "/var/lib/headplane/agent"
  docker:
    enabled: true
    container_name: "headscale"
    socket: "unix:///var/run/docker.sock"
  kubernetes:
    enabled: false
    validate_manifest: true
    pod_name: "headscale"
  proc:
    enabled: false

# OIDC Configuration for authentication
oidc:
  issuer: "https://id.mydomain.tld/.well-known/openid-configuration"
  client_id: "xxxxxx-xxxxxxxxxxx-xxxxxxxx"
  client_secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  disable_api_key_login: true
  token_endpoint_auth_method: "client_secret_post"
  headscale_api_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
  redirect_uri: "https://hp.mydomain.tld/admin/oidc/callback"
  user_storage_file: "/var/lib/headplane/users.json"
