server:
  host: "0.0.0.0"
  port: 3000
  cookie_secret: "e919e1ef413afb3c851aaea648b6bc56" # Change this!
  cookie_secure: true

headscale:
  url: "http://headscale:8080"
  config_path: "/etc/headscale/config.yaml"
  config_strict: true

# Integration configurations
integration:
  docker:
    enabled: true
    container_name: "headscale"
    socket: "unix:///var/run/docker.sock"
  kubernetes:
    enabled: false
    validate_manifest: true
    pod_name: "headscale"
  proc:
    enabled: false
