services:
  web:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    container_name: karakeep-web
    restart: unless-stopped
    volumes:
      - ./app-data:/data
    ports:
      - "127.0.0.1:3210:3000"
      - "100.64.0.6:3210:3000"
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATA_DIR: /data # DON'T CHANGE THIS
      DISABLE_SIGNUPS: true
      DISABLE_PASSWORD_AUTH: false # will set true after checking OICD
      OAUTH_WELLKNOWN_URL: ${OAUTH_WELLKNOWN_URL}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_SCOPE: "openid email profile"
      OAUTH_PROVIDER_NAME: Pocket-ID
      OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: true
      OAUTH_TIMEOUT: 17500
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: karakeep-chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    container_name: karakeep-meilisearch
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ./meilisearch:/meili_data
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
